### ISSUE TITLE
Use new UI API.

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-url#8]
The add-ons SDK has deprecated the widget (?) API. Time to switch the toolbar button code to the new UI API.

**Comment by fwenzel** [comment]
```
console.error: copy-url:
  DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/Promise-backend.js", line 867, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 740, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://jid0-zahxu5e9sjk6vvq8up9tqpnlwuk-at-jetpack/copy-url/lib/main.js", line 6, in null
    widgets = require("widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 625, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);
```
